
splinterdb.dbname=/tmp/splinter.db
splinterdb.disk_size=6442450944000
splinterdb.cache_size=10737418240
splinterdb.max_key_size=28
splinterdb.destroy=false
splinterdb.format=single


splinterdb.use_shmem=false
splinterdb.shmem_size=0


splinterdb.page_size=4096
splinterdb.extent_size=131072


splinterdb.io_flags=66
splinterdb.io_perms=0644
splinterdb.io_async_queue_depth=512


splinterdb.cache_use_stats=false
splinterdb.cache_logfile=


splinterdb.num_memtable_bg_threads=1
splinterdb.num_normal_bg_threads=1


splinterdb.btree_rough_count_height=0
splinterdb.filter_hash_size=0
splinterdb.filter_log_index_size=0


splinterdb.use_log=true
splinterdb.memtable_capacity=268435456


splinterdb.fanout=16
splinterdb.use_stats=0
splinterdb.reclaim_threshold=0
splinterdb.queue_scale_percent=18446744073709551615