
f2.dbname=/tmp/FASTER_test
f2.hot_log_path=hot_log
f2.cold_log_path=cold_log


f2.hot_log_mem=268435456  
f2.cold_log_mem=268435456
f2.hot_index_size=134217728
f2.cold_index_size=4194304
f2.hot_store_budget=32212254720  
f2.cold_store_budget=32212254720  
f2.hot_compaction_threads=1
f2.cold_compaction_threads=1
f2.compaction_threshold=0.3
f2.cold_index_mem_size=268435456
f2.cold_index_mutable_fraction=0.6
f2.cold_store_mutable_fraction=0.5
f2.read_cache_enabled=false
f2.fieldcount=0